#!/bin/bash
# clean up assembly working files if needed
# param is filename

[[ -z "$1" ]] && { echo "missing argument: filename"; exit 1; }

[[ -f "$1.lst" ]] && rm "$1.lst"
[[ -f "$1.o" ]] && rm "$1.o"
[[ -f "$1.map" ]] && rm "$1.map"
[[ -f "$1" ]] && rm "$1"
