#!/bin/bash

# a start on more automation, these so far
# but some of them need review (gdbinit
# for sure)

# bash
ln -sv dotfiles/bashrc .bashrc

# global git
ln -sv dotfiles/gitconfig .gitconfig
ln -sv dotfiles/gitignore .gitignore

# vim
ln -sv dotfiles/gvimrc .gvimrc
ln -sv dotfiles/vimrc .vimrc
ln -sv dotfiles/vim .vim

# misc
ln -sv dotfiles/gdbinit .config/.gdbinit

# these need verification

# also, the following arent' in my dotfiles
# yet but probably should be
# .ssh directory
# .tmux.conf
# .inputrc
# .bash_profile
# .profile
# .minttyrc
# .config/mc

